main_app/urls.py
from django.urls import path
from . import views
from .views import SearchResultsView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('observations/', views.observations_index, name='index'),
    path('observations/<int:observation_id>/', views.observations_detail, name='detail'),
    path('allobservations/', views.allobservations, name='allobservations_index'),
    path('allobservations/<int:observation_id>/', views.allobservations_detail, name='allobservations_detail'),
    path('observations/create/', views.ObservationCreate.as_view(), name='observations_create'),
    path('observations/<int:pk>/update/', views.ObservationUpdate.as_view(), name='observations_update'),
    path('observations/<int:pk>/delete/', views.ObservationDelete.as_view(), name='observations_delete'),
    path('observations/<int:observation_id>/add_location/', views.add_location, name='add_location'),
    path('observations/<int:observation_id>/assoc_category/<int:category_id>/', views.assoc_category, name='assoc_category'),
    path('observations/<int:observation_id>/assoc_category/<int:category_id>/delete', views.assoc_category_delete, name='assoc_category_delete'),
    path('categorys/', views.CategoryList.as_view(), name='categorys_index'),
    path('categorys/<int:pk>/', views.CategoryDetail.as_view(), name='categorys_detail'),
    path('categorys/create/', views.CategoryCreate.as_view(), name='categorys_create'),
    path('categorys/<int:pk>/update/', views.CategoryUpdate.as_view(), name='categorys_update'),
    path('categorys/<int:pk>/delete/', views.CategoryDelete.as_view(), name='categorys_delete'),
    path('observations/<int:observation_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
    path("search/", SearchResultsView.as_view(), name="search_results"),

]

naturalist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

STATES = (
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)

# Create your models here.
class Category(models.Model):
    classification = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.classification}'

    def get_absolute_url(self):
        return reverse('categorys_detail', kwargs={'pk': self.id})


class Observation(models.Model):
    name = models.CharField(max_length=100)
    sciname = models.CharField(max_length=100)
    amount = models.IntegerField()
    description = models.CharField(max_length=250)
    details = models.CharField(max_length=250)
    categorys = models.ManyToManyField(Category)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'observation_id': self.id})

class Location(models.Model):
    date = models.DateField('Date Observed')
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(
        max_length=2,
        choices=STATES,
        default=STATES[0][0]
    )

    observation = models.ForeignKey(Observation, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_state_display()} on {self.date}"

    class Meta:
        ordering = ['-date']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    observation = models.ForeignKey(Observation, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for observation_id: {self.observation_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Location

class LocationForm(ModelForm):
  class Meta:
    model = Location
    fields = ['date', 'name', 'city', 'state']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .forms import LocationForm
from django.db.models import Q
import uuid
import boto3
from .models import Observation, Category, Photo

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'naturalist-avatar'

# HOME VIEW
def home(request):
  return render(request, 'home.html')

# ABOUT VIEW
def about(request):
  return render(request, 'about.html')


# MY OBSERVATION INDEX
@login_required
def observations_index(request):
    # observations = Observation.objects.all()
    observations = Observation.objects.filter(user=request.user)
    return render(request, 'observations/index.html', { 'observations': observations })

# ALL OBSERVATION INDEX
def allobservations(request):
    observations = Observation.objects.all()
    return render(request, 'allobservations/index.html', { 'observations': observations })

def allobservations_detail(request, observation_id):
    observation = Observation.objects.get(id=observation_id)
    return render(request, 'observations/detail.html', {'observation': observation})

# INDIVDUAL OBSERVATION DETAIL
@login_required
def observations_detail(request, observation_id):
    observation = Observation.objects.get(id=observation_id)
    location_form = LocationForm()
    categorys_observation_doesnt_have = Category.objects.exclude(id__in = observation.categorys.all().values_list('id'))
    return render(request, 'observations/detail.html', {
        'observation': observation, 'location_form': location_form,
        'categorys': categorys_observation_doesnt_have
  })

@login_required
def add_location(request, observation_id):
    form = LocationForm(request.POST)
    if form.is_valid():
        new_location = form.save(commit=False)
        new_location.observation_id = observation_id
        new_location.save()
    return redirect('detail', observation_id=observation_id)

# ASSOCIATING OBSERVATION WITH CATEGORY
@login_required
def assoc_category(request, observation_id, category_id):
  Observation.objects.get(id=observation_id).categorys.add(category_id)
  return redirect('detail', observation_id=observation_id)


# DELETING CATEGORY FROM ASSOCIATED OBSERVATION
@login_required
def assoc_category_delete(request, observation_id, category_id):
  Observation.objects.get(id=observation_id).categorys.remove(category_id)
  return redirect('detail', observation_id=observation_id)

# PHOTO UPLOAD
@login_required
def add_photo(request, observation_id):
    # photo-file will be the "name" attribute on the <input type="file">
    # attempt to collect the photo file data
    photo_file = request.FILES.get('photo-file', None)
    # use conditional logic to determine if file is present
    if photo_file:
    # if it's present, we will create a reference to the boto3 client
      s3 = boto3.client('s3')
      #Create unique ide for each photo file
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      #upload the photo phile to aws
      try:
      # if successful
        s3.upload_fileobj(photo_file, BUCKET, key)
        # take the exchanged url and save it to the database
        url = f"{S3_BASE_URL}{BUCKET}/{key}"
          # 1. create photo instance with phot model and provide cat_id as foreign key value
        photo = Photo(url=url, observation_id=observation_id)
          # 2. save the photo instance to the database
        photo.save()
      # print an error message
      except Exception as error:
        print('An error occurred uploading file to S3')
    # redirect the user to the origin page
        return redirect('detail', observation_id=observation_id)
    return redirect('detail', observation_id=observation_id)
  # need a unique "key" for S3 / needs image file extension too 

def signup(request):
  error_message = ''
   # check if the request method is post
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    # create a new user because from was submitted
    # use the form data from the request to create a form/model instance from the model from
    form = UserCreationForm(request.POST)
    # validate the form to ensure it was complete
    if form.is_valid():
      # saving the user object to the database
      # This will add the user to the database
      user = form.save()
      # login the user (creates a session for the logged in user in the database)
      # This is how we log a user in via code
      login(request, user)
      # redirect user to cats index page
      return redirect('index')
    # if form not valid redirect user to signup page with an error message
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  # else the request is GET == the user clicked on the signup link
  # create a blank instance of the model form
  form = UserCreationForm()
  # provide that form instance to a registration template
  context = {'form': form, 'error_message': error_message}
  # render the template so the user can fill out the form
  return render(request, 'registration/signup.html', context)

class ObservationCreate(LoginRequiredMixin, CreateView):
    model = Observation
    fields = ['name', 'sciname', 'amount', 'description', 'details']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ObservationUpdate(LoginRequiredMixin, UpdateView):
  model = Observation
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['name', 'sciname', 'amount', 'description', 'details']

class ObservationDelete(LoginRequiredMixin, DeleteView):
  model = Observation
  success_url = '/observations/'

class CategoryList(LoginRequiredMixin, ListView):
  model = Category
  template_name = 'categorys/index.html'

class CategoryDetail(LoginRequiredMixin, DetailView):
  model = Category
  template_name = 'categorys/detail.html'

class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['classification']


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['classification']


class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = '/categorys/'

class SearchResultsView(LoginRequiredMixin, ListView):
    model = Observation
    template_name = "search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Observation.objects.filter(
            Q(name__icontains=query)
        )
        return object_list

main_app/templates/observations/detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ observation.name}} Details</h1>

<div class="row">
<div class="col s6">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ observation.name }}</span>
    <p>Scientific Name: {{ observation.sciname }}</p>
    <p>Amount: {{ observation.amount }}</p>
    <p>Description: {{ observation.description }}</p>
    <p>Details: {{ observation.details }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'observations_update' observation.id %}">Edit</a>
    <a href="{% url 'observations_delete' observation.id %}">Delete</a>
  </div>
</div>

{% for photo in observation.photo_set.all %}
<img class="responsive-img card-panel" src="{{photo.url}}" />
{% empty %}
<div class="card-panel teal-text center-align">No Photos Uploaded</div>
{% endfor %}
<form
  action="{% url 'add_photo' observation.id %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}
  <input type="file" name="photo-file" />
  <br /><br />
  <input type="submit" class="btn teal darken-4" value="Upload Photo" />
</form>
</div>
<div class="col s6">
    <form action="{% url 'add_location' observation.id %}" method="post">
      {% csrf_token %} {{ location_form.as_p }}
      <input type="submit" class="btn teal darken-4" value="Add Location" />
    </form>
    <br />

    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Location</th>
          <th>City</th>
          <th>State</th>
        </tr>
      </thead>
      <tbody>
        {% for location in observation.location_set.all %}
        <tr>
          <td>{{location.date}}</td>
          <td>{{location.name}}</td>
          <td>{{location.city}}</td>
          <td>{{location.get_state_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr />
<div class="row">
    <div class="col s6">
      <h3>{{ observation.name }}'s Category</h3>
      {% if observation.categorys.count %} {% for category in observation.categorys.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <span>{{ category.classification }}</span>
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_category_delete' observation.id category.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn deep-orange darken-4">Remove</button>
          </form>
        </div>
      </div>
      {% endfor %} {% else %}
      <h5>No Category :(</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Categories</h3>
      {% if categorys.count %} {% for category in categorys.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <span>
            {{ category.classification }}
          </span></span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_category' observation.id category.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn teal darken-4">Add</button>
          </form>
        </div>
      </div>
      {% endfor %} {% else %}
      <h5>{{observation.classification}} Already Has All Classifications Available</h5>
      {% endif %}
    </div>
  <script>
    var dateEl = document.getElementById("id_date");
    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });

    var selectEl = document.getElementById("id_state");
    M.FormSelect.init(selectEl);
  </script>

{% endblock %}
</div>

main_app/templates/observations/index.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link
rel="stylesheet"
type="text/css"
href="{% static 'css/style.css' %}"
/>
<h1>Observations</h1>

<form action="{% url 'search_results' %}" method="get">
    <input name="q" type="text" placeholder="Search...">
  </form>

{% for observation in observations %}
<div class="row">
    <div class="col s4 m7">
<div class="card medium hoverable">
    <a href="{% url 'detail' observation.id %}">
  <div class="card-content">
    <span class="card-title">{{ observation.name }}</span>
    <div class="card-image">
    {% for photo in observation.photo_set.all %}
<img class="responsive-img card-panel" src="{{photo.url}}" />
{% endfor %}
</div></div>
  </div>
  </div>
  </div>
</a>
</div>
{% endfor %} {% endblock %}